#include <stdio.h>

int main(void) {

    //Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    //1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    //By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

    //a3 currently processed Fibonacci number
    //a1, a2 Fibonacci Sequence
    //sum, sum of all even Fibonacci numbers
    int a1 = 1, a2 = 1, a3 = 2, sum = 0;

    //does not exceed 4mill
    while (a3 < 4000000) {
        //sum of first two numbers
        a3 = a1 + a2;
        //add the value of a3 to sum if it is an even number
        sum += a3 * !(a3%2);
        //set to next number for the Fibonacci Series
        a1 = a2;
        a2 = a3;
    }

    printf("%u\n", sum);

    return 0;
}

